// <auto-generated />
using ApiConsultarProduto.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiConsultarProduto.Migrations
{
    [DbContext(typeof(ApiConsultarProdutoContext))]
    partial class ApiConsultarProdutoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ApiConsultarProduto.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id_produto");

                    b.Property<string>("CodigoDeBarras")
                        .HasColumnName("cb_produto");

                    b.Property<string>("Descricao")
                        .HasColumnName("dc_produto");

                    b.Property<string>("Marca");

                    b.Property<string>("Nome")
                        .HasColumnName("nm_produto");

                    b.HasKey("Id");

                    b.ToTable("produto","dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
